package MY_THEME

import "github.com/ecsaas/mongo-define-config/DEFINE_VARIABLES/MONGO_DATABASE/DEFAULT_KEY"

const ID = DEFAULT_KEY.ID
const CREATED = DEFAULT_KEY.CREATED
const CREATED_UNIX = DEFAULT_KEY.CREATED_UNIX
const UPDATED = DEFAULT_KEY.UPDATED
const UPDATED_UNIX = DEFAULT_KEY.UPDATED_UNIX
const ROOT_USER_ID = DEFAULT_KEY.ROOT_USER_ID

const MY_THEME_STATUS = "myThemeStatus"
const MY_THEME_NAME = "myThemeName"
const MY_THEME_DATA = "myThemeData"

const THEME_ID = "themeId"
const THEME_CATEGORY = "themeCategory"
