package GOOGLE_USER

import "github.com/ecsaas/mongo-define-config/DEFINE_VARIABLES/MONGO_DATABASE/DEFAULT_KEY"

const ID = DEFAULT_KEY.ID
const CREATED = DEFAULT_KEY.CREATED
const CREATED_UNIX = DEFAULT_KEY.CREATED_UNIX
const UPDATED = DEFAULT_KEY.UPDATED
const UPDATED_UNIX = DEFAULT_KEY.UPDATED_UNIX

const SUB = "sub"
const CONNECT_TOKEN = "connectToken"
